#!/usr/bin/env bash
# Detect the host OS and (re)generate fastcodon/sys/config.codon with the matching compile-time
# platform literals. Run once after cloning on Linux/macOS:   ./scripts/setup.sh
set -euo pipefail
repo="$(cd "$(dirname "$0")/.." && pwd)"
cfg="$repo/fastcodon/sys/config.codon"

case "$(uname -s)" in
  Darwin) win=0; apple=1; name=darwin ;;
  Linux)  win=0; apple=0; name=linux  ;;
  *)      win=0; apple=0; name=linux  ;;   # treat unknown unix as linux (epoll)
esac

cat > "$cfg" <<EOF
# fastcodon.sys.config — GENERATED by scripts/setup.sh for: $name
IS_WINDOWS: Literal[int] = $win
IS_APPLE: Literal[int] = $apple
IS_LINUX: Literal[int] = 0 if (IS_WINDOWS or IS_APPLE) else 1


def platform_name() -> str:
    if IS_WINDOWS:
        return "windows"
    elif IS_APPLE:
        return "darwin"
    else:
        return "linux"
EOF
echo "wrote $cfg ($name)"
