# Detect the host OS and (re)generate fastcodon/sys/config.codon with the matching compile-time
# platform literals. Run once after cloning on Windows.   PS> .\scripts\setup.ps1
$repo = Split-Path -Parent $PSScriptRoot
$cfg  = Join-Path $repo "fastcodon\sys\config.codon"
$isWin = 1; $isApple = 0    # this script only runs on Windows
$body = @"
# fastcodon.sys.config — GENERATED by scripts/setup.ps1 for: windows
IS_WINDOWS: Literal[int] = $isWin
IS_APPLE: Literal[int] = $isApple
IS_LINUX: Literal[int] = 0 if (IS_WINDOWS or IS_APPLE) else 1


def platform_name() -> str:
    if IS_WINDOWS:
        return "windows"
    elif IS_APPLE:
        return "darwin"
    else:
        return "linux"
"@
Set-Content -Path $cfg -Value $body -Encoding utf8
Write-Host "wrote $cfg (windows)"
